apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: argo-rollouts-manager
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: argo-rollouts-manager
  name: argo-rollouts-manager-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
