---
# Secrets for MySQL
apiVersion: v1
kind: Secret  # what resource you are going to create
metadata:
  name: mysql-secret  # information abt the resource
type: Opaque       
data:                 # store the data in environmental variables.
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=
  MYSQL_DATABASE: YmFua2FwcGRi    # bas64 encrypted { echo -n "test123"| base64 }
---
# ConfigMap for MySQL
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "bankappdb"
---
# Storage Class for EBS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com   #  Responsible for dynamically creating thee resource.
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain          # Retain / Delete { volume will be present even after pvc is deleted.}
volumeBindingMode: WaitForFirstConsumer   # {volume created by storage class is going to be created on the same availability zone as the pod. }
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:                       # specification
  accessModes:
    - ReadWriteOnce         # volume should be accessed by one pod at a time.
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
---
# MySQL Deployment
apiVersion: apps/v1  
kind: Deployment  
metadata:
  name: mysql   # metadata name
spec:           # specification/ configuration for the deployment which is created.
  selector:     # define information like which are the pods that are going to be manage  by this deployment.
    matchLabels:  
      app: mysql  # pods that are labeled with app:mysql should be managed by this deployment as per line no.49 & lineno.63
  strategy:       # strategy to define how new pods will be created.
    type: Recreate  # Ensuring old pod are terminated before the new pods are created.
  template:         # template for the pod to be created { Information of docker image, docker container, username & password}
    metadata:       
      labels:       # under template we are defining the label for the pod.
        app: mysql
    spec:           # specification/configuration for the pod { details like container to use}
      containers:
      - image: mysql:8   # name of the image to use for creating the container
        name: mysql
        resources:      # 2 resources should be defined like requests ( min gauranteed ram & cpu )and limits ( max ram & cpu that can be utilized.)
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:             # environment variables to use for username and password.
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:     # Refernce from the secret no 4.
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:  # Reference from the configmap
              name: mysql-config
              key: MYSQL_DATABASE
        ports:      
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql  # path inside the container
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service  # name of the service
spec:
  ports:
  - port: 3306        # port exposed by the service
    targetPort: 3306  # port opened by the container
  selector:
    app: mysql       # information about the pod which is defined in the deployment over the line no 59.
---
# BankApp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1  # no of replicas required { no of pods replicas to run this deployment}
  selector:
    matchLabels:
      app: bankapp
  template:     # structure of pod tem
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: adijaiswal/bankapp:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
---
# BankApp Service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp
