# permissions for end users to edit rolloutmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rolloutmanagers-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: argo-rollouts-manager
    app.kubernetes.io/part-of: argo-rollouts-manager
    app.kubernetes.io/managed-by: kustomize
  name: rolloutmanagers-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - rolloutmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - rolloutmanagers/status
  verbs:
  - get
